### ISSUE TITLE
Wrap Query() calls in a retry wrapper

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/metamist#700]
# Problem

RE:  https://github.com/populationgenomics/metamist/blob/45d22459cb8ef787a877dc7a5e7ecbf7274557e3/metamist/graphql/__init__.py#L140

I've seen many instances where starting the pipeline, registering results in metamist, or other frequent queries have brought down metamist. Part of this is due to the way that these queries are constructed - pull all results for a specific project, then move on to the next project and repeat.

## Pipeline

1. We run the pipeline with a number of input datasets (for seqr_loader pipeline runs this could contain 15-20 separate projects)
2. At startup queries run for each dataset in turn, gathering relevant participants/SG IDs
3. (in future) pull all analysis entries for all SG IDs, and use those as a source of truth for presence of files in GCP

## GATK-SV

For GATK-SV I periodically run [a query script](https://github.com/populationgenomics/production-pipelines-configuration/blob/main/config/gatk-sv/find_called_samples.py) across all datasets, using the analysis db entries to identify which samples require new data to be generated. At the moment I run this locally, and it's also prone to failure.

## AIP

I have a script called [report_hunter](https://github.com/populationgenomics/automated-interpretation-pipeline/blob/main/helpers/report_hunter.py), which runs as a cron task under the `talos` project in GCP. This queries for all AIP analysis entries in all projects, and creates an index page for analysts to use. [This fails more times than not](https://batch.hail.populationgenomics.org.au/batches/434832/jobs/1).

## Solution?

For AIP I put together a minimal backoff retry wrapper [here](https://github.com/populationgenomics/automated-interpretation-pipeline/blob/dda0c01f2647853674807eb6dee32c62a7ec0adb/reanalysis/utils.py#L72), and all of my problems went away. This is nothing special, just a try: retry catch block, but since then I've seen 0 failures.

Instead of adding this everywhere that uses metamist, can we patch this at source? Maybe something more robust like https://github.com/litl/backoff would be a good solution to wrap the query/async_query methods

**Comment by MattWellie** [comment]
@EddieLF  has recently seen a chunk of consecutive failures:
https://batch.hail.populationgenomics.org.au/batches/439446/jobs/1
https://batch.hail.populationgenomics.org.au/batches/439448/jobs/1
https://batch.hail.populationgenomics.org.au/batches/439454/jobs/1

**Comment by MattWellie** [comment]
Example traceback for flavour:

```
2024-04-03 01:25:18 INFO (root 246): Getting sequencing groups for dataset PROJECT_1
2024-04-03 01:25:19 INFO (root 246): Getting sequencing groups for dataset PROJECT_2

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gql/transport/requests.py", line 260, in execute
    result = response.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gql/transport/requests.py", line 248, in raise_response_error
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: https://sample-metadata-api-mnrpw3mdza-ts.a.run.app/graphql

The above exception was the direct cause of the following exception:
```
